In [50]:
from overcooked_ai.overcooked_ai_py.utils import load_pickle, load_pkl, save_pickle, load_dict_from_file, profile

import copy
import numpy as np

In [17]:
hh_performance = load_pickle('human_aware_rl/data/human/anonymized/hh_performance.pickle')

In [18]:
hh_performance

{'random0': (94.0, 8.024961059095551),
 'random1': (84.61538461538461, 3.8638645484768066),
 'random3': (66.66666666666667, 3.1426968052735447),
 'simple': (97.5, 4.284784125250653),
 'unident_s': (158.33333333333334, 7.9785592313028175)}

In [19]:
hh_losses = load_pickle('human_aware_rl/data/human/anonymized/hh_losses_data.pickle')

In [20]:
hh_losses

{'random0': {'BC_Test': {'acc': 0.6033022876297899,
   'loss': 1.1302079607754847},
  'BC_Train': {'acc': 0.6011623715894643, 'loss': 1.1767536335548445},
  'PBT': {'acc': [0.11180383659583983,
    0.09964489350388618,
    0.106786429941381,
    0.10500829540025022,
    0.1042496365752913],
   'loss': [5.5232860196687925,
    3.3953892311293976,
    5.592753055728737,
    4.3959229365168015,
    4.385655169605727]},
  'PPO_SP': {'acc': [0.11012928166182638,
    0.10126697155131521,
    0.10305697218345686,
    0.10843903161178065,
    0.10574855811278548],
   'loss': [3.6976386441981504,
    4.466567325396291,
    3.676852962910889,
    4.26905339289222,
    3.34360319387899]}},
 'random1': {'BC_Test': {'acc': 0.47707458861416313,
   'loss': 1.3926107867802668},
  'BC_Train': {'acc': 0.47516160988307676, 'loss': 1.3852539426214714},
  'PBT': {'acc': [0.23288765828120064,
    0.22482091713825922,
    0.24987291334530898,
    0.22487845006165977,
    0.25448443310092983],
   'loss': [3.8

In [21]:
clean_main_trials = load_pkl('human_aware_rl/data/human/anonymized/clean_main_trials.pkl')

In [22]:
clean_main_trials

Unnamed: 0  Unnamed: 0.1  cur_gameloop      datetime  is_leader  \
0                0         14459           0.0  1.557859e+12       True   
1                1         14460           1.0  1.557859e+12       True   
2                2         14461           2.0  1.557859e+12       True   
3                3         14462           3.0  1.557859e+12       True   
4                4         14463           4.0  1.557859e+12       True   
...            ...           ...           ...           ...        ...   
143208      143208        181687         639.0  1.557970e+12       True   
143209      143209        181688         640.0  1.557970e+12       True   
143210      143210        181689         641.0  1.557970e+12       True   
143211      143211        181690         642.0  1.557970e+12       True   
143212      143212        181691         643.0  1.557970e+12       True   

            joint_action                                         layout  \
0       [[0, 0], [0, 0]]           ['XXPXX', 'O  2O', 'X1  X', 'XDXSX']   
1       [[0, 0], [0, 0]]           ['XXPXX', 'O  2O', 'X1  X', 'XDXSX']   
2       [[0, 0], [0, 0]]           ['XXPXX', 'O  2O', 'X1  X', 'XDXSX']   
3       [[0, 0], [0, 0]]           ['XXPXX', 'O  2O', 'X1  X', 'XDXSX']   
4       [[0, 0], [0, 0]]           ['XXPXX', 'O  2O', 'X1  X', 'XDXSX']   
...                  ...                                            ...   
143208  [[0, 0], [0, 0]]  ['XXXPX', 'O X1P', 'O2X X', 'D X X', 'XXXSX']   
143209  [[0, 0], [0, 0]]  ['XXXPX', 'O X1P', 'O2X X', 'D X X', 'XXXSX']   
143210  [[0, 0], [0, 0]]  ['XXXPX', 'O X1P', 'O2X X', 'D X X', 'XXXSX']   
143211  [[0, 0], [0, 0]]  ['XXXPX', 'O X1P', 'O2X X', 'D X X', 'XXXSX']   
143212  [[0, 0], [0, 0]]  ['XXXPX', 'O X1P', 'O2X X', 'D X X', 'XXXSX']   

         layout_name                                         next_state  \
0       cramped_room  {'players': [{'position': [1, 2], 'orientation...   
1       cramped_room  {'players': [{'position': [1, 2], 'orientation...   
2       cramped_room  {'players': [{'position': [1, 2], 'orientation...   
3       cramped_room  {'players': [{'position': [1, 2], 'orientation...   
4       cramped_room  {'players': [{'position': [1, 2], 'orientation...   
...              ...                                                ...   
143208       random0  {'players': [{'position': [3, 1], 'orientation...   
143209       random0  {'players': [{'position': [3, 1], 'orientation...   
143210       random0  {'players': [{'position': [3, 1], 'orientation...   
143211       random0  {'players': [{'position': [3, 1], 'orientation...   
143212       random0  {'players': [{'position': [3, 1], 'orientation...   

        reward  ...                                              state  \
0          0.0  ...  {'players': [{'position': [1, 2], 'orientation...   
1          0.0  ...  {'players': [{'position': [1, 2], 'orientation...   
2          0.0  ...  {'players': [{'position': [1, 2], 'orientation...   
3          0.0  ...  {'players': [{'position': [1, 2], 'orientation...   
4          0.0  ...  {'players': [{'position': [1, 2], 'orientation...   
...        ...  ...                                                ...   
143208     0.0  ...  {'players': [{'position': [3, 1], 'orientation...   
143209     0.0  ...  {'players': [{'position': [3, 1], 'orientation...   
143210     0.0  ...  {'players': [{'position': [3, 1], 'orientation...   
143211     0.0  ...  {'players': [{'position': [3, 1], 'orientation...   
143212     0.0  ...  {'players': [{'position': [3, 1], 'orientation...   

       time_elapsed  time_left is_wait  completed    run  workerid_num  \
0             0.154      180.0    True       True  run-1             0   
1             0.312      180.0    True       True  run-1             0   
2             0.461      180.0    True       True  run-1             0   
3             0.614      179.0    True       True  run-1             0   
4             1.043      179.0    True       T

In [29]:
clean_train_trials = load_pkl('human_aware_rl/data/human/anonymized/clean_train_trials.pkl')
clean_test_trials = load_pkl('human_aware_rl/data/human/anonymized/clean_test_trials.pkl')

In [30]:
clean_train_trials

Unnamed: 0  Unnamed: 0.1  cur_gameloop      datetime  is_leader  \
13235        13235         35204           0.0  1.557859e+12       True   
13236        13236         35205           1.0  1.557859e+12       True   
13237        13237         35206           2.0  1.557859e+12       True   
13238        13238         35207           3.0  1.557859e+12       True   
13239        13239         35208           4.0  1.557859e+12       True   
...            ...           ...           ...           ...        ...   
125116      125116        150899        1199.0  1.557969e+12       True   
125117      125117        150900        1200.0  1.557969e+12       True   
125118      125118        150901        1201.0  1.557969e+12       True   
125119      125119        150902        1202.0  1.557969e+12       True   
125120      125120        150903        1203.0  1.557969e+12       True   

            joint_action                                             layout  \
13235   [[0, 0], [0, 0]]  ['XXXXXXXXX', 'O XSXOX S', 'X   P 1 X', 'X2  P...   
13236   [[0, 0], [0, 0]]  ['XXXXXXXXX', 'O XSXOX S', 'X   P 1 X', 'X2  P...   
13237   [[0, 0], [0, 0]]  ['XXXXXXXXX', 'O XSXOX S', 'X   P 1 X', 'X2  P...   
13238   [[0, 0], [0, 0]]  ['XXXXXXXXX', 'O XSXOX S', 'X   P 1 X', 'X2  P...   
13239   [[0, 0], [0, 0]]  ['XXXXXXXXX', 'O XSXOX S', 'X   P 1 X', 'X2  P...   
...                  ...                                                ...   
125116  [[0, 0], [0, 0]]  ['XXXPPXXX', 'X      X', 'D XXXX S', 'X2    1X...   
125117  [[0, 0], [0, 0]]  ['XXXPPXXX', 'X      X', 'D XXXX S', 'X2    1X...   
125118  [[0, 0], [0, 0]]  ['XXXPPXXX', 'X      X', 'D XXXX S', 'X2    1X...   
125119  [[0, 0], [0, 0]]  ['XXXPPXXX', 'X      X', 'D XXXX S', 'X2    1X...   
125120  [[0, 0], [0, 0]]  ['XXXPPXXX', 'X      X', 'D XXXX S', 'X2    1X...   

                  layout_name  \
13235   asymmetric_advantages   
13236   asymmetric_advantages   
13237   asymmetric_advantages   
13238   asymmetric_advantages   
13239   asymmetric_advantages   
...                       ...   
125116                random3   
125117                random3   
125118                random3   
125119                random3   
125120                random3   

                                               next_state  reward  ...  \
13235   {'players': [{'position': [6, 2], 'orientation...     0.0  ...   
13236   {'players': [{'position': [6, 2], 'orientation...     0.0  ...   
13237   {'players': [{'position': [6, 2], 'orientation...     0.0  ...   
13238   {'players': [{'position': [6, 2], 'orientation...     0.0  ...   
13239   {'players': [{'position': [6, 2], 'orientation...     0.0  ...   
...                                                   ...     ...  ...   
125116  {'players': [{'position': [4, 3], 'orientation...     0.0  ...   
125117  {'players': [{'position': [4, 3], 'orientation...     0.0  ...   
125118  {'players': [{'position': [4, 3], 'orientation...     0.0  ...   
125119  {'players': [{'position': [4, 3], 'orientation...     0.0  ...   
125120  {'players': [{'position': [4, 3], 'orientation...     0.0  ...   

                                                    state time_elapsed  \
13235   {'players': [{'position': [6, 2], 'orientation...        0.152   
13236   {'players': [{'position': [6, 2], 'orientation...        0.301   
13237   {'players': [{'position': [6, 2], 'orientation...        0.453   
13238   {'players': [{'position': [6, 2], 'orientation...        0.602   
13239   {'players': [{'position': [6, 2], 'orientation...        0.751   
...                                                   ...          ...   
125116  {'players': [{'position': [4, 3], 'orientation...      180.002   
125117  {'players': [{'position': [4, 3], 'orientation...      180.151   
125118  {'players': [{'position': [4, 3], 'orientation...      180.301   
125119  {'players': [{'position': [4, 3], 'orientation...      180.451   
125120  {'players': [{'position': [4, 3], 'orientation... 

In [31]:
clean_train_trials['workerid_num'].unique()

array([ 2,  3, 11, 12, 13, 14, 16, 20, 22,  1, 17, 18,  4, 10, 15, 19])

In [32]:
clean_main_trials['workerid_num'].unique()

array([ 0,  1,  2,  3,  4,  6,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 22, 23])

In [33]:
clean_test_trials['workerid_num'].unique()

array([ 1,  4, 10, 15, 17, 18, 19, 23, 13, 16, 20, 22,  2, 14,  3, 11, 12])

In [38]:
clean_main_trials.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'cur_gameloop', 'datetime', 'is_leader',
       'joint_action', 'layout', 'layout_name', 'next_state', 'reward',
       'round_num', 'round_type', 'score', 'state', 'time_elapsed',
       'time_left', 'is_wait', 'completed', 'run', 'workerid_num',
       'reward_norm', 'cur_gameloop_total', 'reward_norm_total'],
      dtype='object')

In [41]:
clean_train_trials['round_num'].unique()

array([1., 2., 0., 4., 3.])

In [44]:
import pandas as pd
clean_trials = pd.concat([clean_train_trials, clean_test_trials])

In [45]:
clean_trials.to_pickle('human_aware_rl/data/human/anonymized/clean_trials.pkl')